/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayJobIdRouteImport } from './routes/pay.$jobId'
import { Route as DmArtisanIdRouteImport } from './routes/dm.$artisanId'
import { Route as ChatJobIdRouteImport } from './routes/chat.$jobId'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as ArtisanIdRouteImport } from './routes/artisan.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayJobIdRoute = PayJobIdRouteImport.update({
  id: '/pay/$jobId',
  path: '/pay/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const DmArtisanIdRoute = DmArtisanIdRouteImport.update({
  id: '/dm/$artisanId',
  path: '/dm/$artisanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatJobIdRoute = ChatJobIdRouteImport.update({
  id: '/chat/$jobId',
  path: '/chat/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanIdRoute = ArtisanIdRouteImport.update({
  id: '/artisan/$id',
  path: '/artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/wallet': typeof WalletRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/book/$id': typeof BookIdRoute
  '/chat/$jobId': typeof ChatJobIdRoute
  '/dm/$artisanId': typeof DmArtisanIdRoute
  '/pay/$jobId': typeof PayJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/wallet': typeof WalletRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/book/$id': typeof BookIdRoute
  '/chat/$jobId': typeof ChatJobIdRoute
  '/dm/$artisanId': typeof DmArtisanIdRoute
  '/pay/$jobId': typeof PayJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/wallet': typeof WalletRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/book/$id': typeof BookIdRoute
  '/chat/$jobId': typeof ChatJobIdRoute
  '/dm/$artisanId': typeof DmArtisanIdRoute
  '/pay/$jobId': typeof PayJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/sos'
    | '/wallet'
    | '/artisan/$id'
    | '/book/$id'
    | '/chat/$jobId'
    | '/dm/$artisanId'
    | '/pay/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/sos'
    | '/wallet'
    | '/artisan/$id'
    | '/book/$id'
    | '/chat/$jobId'
    | '/dm/$artisanId'
    | '/pay/$jobId'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/sos'
    | '/wallet'
    | '/artisan/$id'
    | '/book/$id'
    | '/chat/$jobId'
    | '/dm/$artisanId'
    | '/pay/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RewardsRoute: typeof RewardsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SosRoute: typeof SosRoute
  WalletRoute: typeof WalletRoute
  ArtisanIdRoute: typeof ArtisanIdRoute
  BookIdRoute: typeof BookIdRoute
  ChatJobIdRoute: typeof ChatJobIdRoute
  DmArtisanIdRoute: typeof DmArtisanIdRoute
  PayJobIdRoute: typeof PayJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$jobId': {
      id: '/pay/$jobId'
      path: '/pay/$jobId'
      fullPath: '/pay/$jobId'
      preLoaderRoute: typeof PayJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$artisanId': {
      id: '/dm/$artisanId'
      path: '/dm/$artisanId'
      fullPath: '/dm/$artisanId'
      preLoaderRoute: typeof DmArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$jobId': {
      id: '/chat/$jobId'
      path: '/chat/$jobId'
      fullPath: '/chat/$jobId'
      preLoaderRoute: typeof ChatJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$id': {
      id: '/artisan/$id'
      path: '/artisan/$id'
      fullPath: '/artisan/$id'
      preLoaderRoute: typeof ArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RewardsRoute: RewardsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SosRoute: SosRoute,
  WalletRoute: WalletRoute,
  ArtisanIdRoute: ArtisanIdRoute,
  BookIdRoute: BookIdRoute,
  ChatJobIdRoute: ChatJobIdRoute,
  DmArtisanIdRoute: DmArtisanIdRoute,
  PayJobIdRoute: PayJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
